#############################################################################
# Makefile for building: SpotLite
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  SpotLite.pro
# Template: app
# Command: C:\Qt\5.15.2-msvc2019\bin\qmake.exe -o Makefile SpotLite.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = C:\Qt\5.15.2-msvc2019\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.15.2-msvc2019\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.15.2-msvc2019\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = windows.res
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE) FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: SpotLite.pro ..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\qmake.conf ..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\spec_pre.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\common\angle.conf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\common\windows-desktop.conf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\win32\windows_vulkan_sdk.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\common\windows-vulkan.conf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\common\msvc-desktop.conf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\qconfig.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext__clip2tri.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext__clipper.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext__poly2tri.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_freetype.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_harfbuzz.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_libEGL.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_libGLESv2.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_libpng.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_openwnn.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_pcre2.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_pinyin.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_preprocessor.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_tcime.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_translator.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3danimation.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3danimation_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dcore.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dcore_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dextras.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dextras_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dinput.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dinput_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dlogic.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dlogic_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquick.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquick_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickanimation.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickanimation_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickextras.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickextras_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickinput.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickinput_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickrender.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickrender_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickscene2d.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickscene2d_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3drender.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3drender_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_axbase.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_axbase_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axbase.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axserver_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_bluetooth.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_bluetooth_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_bodymovin_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_bodymovin_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_charts.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_charts_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_core.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_core_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_datavisualization.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_datavisualization_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_dbus_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_designer.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_designer_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_designer_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_designercomponents_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_edid_support_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_gamepad.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_gamepad_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_gui_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_help.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_help_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_help.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_help_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_location.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_location_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_location.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_location_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_multimedia_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_network.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_network_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_networkauth.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_networkauth_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_networkauth.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_nfc.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_nfc_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_packetprotocol_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_pdf.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_pdf_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_pdf.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_pdfwidgets.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_pdfwidgets_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_pdfwidgets.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_positioning.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_positioning_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_positioning_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_positioningquick.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_positioningquick_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_positioningquick.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_positioningquick_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_purchasing.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_purchasing_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_purchasing.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qml.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qml_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qml_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmldebug_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmldevtools_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmlmodels.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmlmodels_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmlmodels.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmltest.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmltest_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmlworkerscript.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmlworkerscript_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3d.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3d_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick3d.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3dassetimport.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3dassetimport_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3drender.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3drender_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick3drender.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3druntimerender.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3druntimerender_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3dutils.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3dutils_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick3dutils.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickcontrols2.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickcontrols2_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickparticles_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickshapes_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quicktemplates2.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quicktemplates2_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_remoteobjects.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_remoteobjects_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_repparser.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_repparser_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_repparser.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_repparser_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_script.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_script_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_script.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_scripttools.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_scripttools_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_scripttools.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_scxml.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_scxml_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_scxml_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_sensors.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_sensors_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_sensors_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_serialbus.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_serialbus_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_serialport.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_serialport_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_sql_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_svg.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_svg_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_testlib_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_texttospeech.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_texttospeech_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_uiplugin.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_uiplugin.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_uitools.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_uitools_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_uitools_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_virtualkeyboard.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_virtualkeyboard_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webchannel.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webchannel_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webengine.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webengine_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webengine.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webenginecore.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webenginecore_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webenginecoreheaders_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webenginewidgets.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webenginewidgets_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_websockets.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_websockets_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_websockets_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_webview.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_webview_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_winextras.pri \
		..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_winextras_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_winextras.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_xmlpatterns.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_xmlpatterns_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_balsam.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_canbusutil.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_dumpcpp.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_dumpdoc.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lconvert.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lprodump.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lrelease-pro.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lrelease.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lupdate-pro.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lupdate.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_meshdebug.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_moc.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qcollectiongenerator.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qdbuscpp2xml.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qdbusxml2cpp.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qgltf.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qhelpgenerator.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qlalr.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qml.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlcachegen.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlformat.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlimportscanner.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmllint.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlmin.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlplugindump.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlpreview.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlprofiler.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlscene.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmltestrunner.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmltyperegistrar.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qscxmlc.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qtattributionsscanner.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qvkgen.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qwebengine_convert_dict.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_rcc.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_repc.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_tracegen.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_uic.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_xmlpatterns.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_xmlpatternsvalidator.pri \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\qt_functions.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\qt_config.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\win32-msvc\qmake.conf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\qmake.conf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\spec_post.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\common\msvc-version.conf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\toolchain.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\default_pre.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\resolve_config.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\default_post.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\win32\windows.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\precompile_header.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\warn_on.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\qt.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\resources_functions.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\resources.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\moc.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\win32\opengl.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\uic.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\qmake_use.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\file_copies.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\testcase_targets.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\exceptions.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\yacc.prf \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\lex.prf \
		SpotLite.pro \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebEngineWidgets.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebEngineCore.prl \
		..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Positioning.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5XmlPatterns.prl \
		..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Quick.prl \
		..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5QmlModels.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebChannel.prl \
		..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Qml.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5PrintSupport.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Widgets.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Gui.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Sql.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Network.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Core.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\qtmain.prl \
		.qmake.stash \
		..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\build_pass.prf \
		res\icons.qrc \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebEngineWidgetsd.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebEngineCored.prl \
		..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Positioningd.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5XmlPatternsd.prl \
		..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Quickd.prl \
		..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5QmlModelsd.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebChanneld.prl \
		..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Qmld.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5PrintSupportd.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Widgetsd.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Guid.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Sqld.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Networkd.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Cored.prl \
		..\..\..\..\Qt\5.15.2-msvc2019\lib\qtmaind.prl
	$(QMAKE) -o Makefile SpotLite.pro
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\spec_pre.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\common\angle.conf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\common\windows-desktop.conf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\win32\windows_vulkan_sdk.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\common\windows-vulkan.conf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\common\msvc-desktop.conf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\qconfig.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext__clip2tri.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext__clipper.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext__poly2tri.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_freetype.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_harfbuzz.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_libEGL.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_libGLESv2.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_libpng.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_openwnn.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_pcre2.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_pinyin.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_preprocessor.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_tcime.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_ext_translator.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3danimation.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3danimation_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3danimation.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3danimation_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dcore.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dcore_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dcore_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dextras.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dextras_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dextras_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dinput.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dinput_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dinput_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dlogic.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dlogic_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquick.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquick_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquick_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickanimation.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickanimation_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickextras.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickextras_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickinput.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickinput_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickrender.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickrender_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickscene2d.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3dquickscene2d_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3drender.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_3drender_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_axbase.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_axbase_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_axserver_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_bluetooth.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_bluetooth_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_bodymovin_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_bodymovin_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_charts.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_charts_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_charts.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_core.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_core_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_datavisualization.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_datavisualization_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_dbus_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_designer.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_designer_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_designer.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_designer_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_designercomponents_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_edid_support_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_gamepad.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_gamepad_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_gamepad.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_gui.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_gui_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_help.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_help_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_help.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_help_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_location.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_location_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_location.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_location_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_multimedia_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_multimedia_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_network.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_network_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_networkauth.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_networkauth_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_networkauth.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_nfc.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_nfc_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_packetprotocol_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_pdf.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_pdf_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_pdf.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_pdfwidgets.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_pdfwidgets_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_pdfwidgets.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_positioning.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_positioning_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_positioning_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_positioningquick.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_positioningquick_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_positioningquick.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_positioningquick_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_printsupport_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_purchasing.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_purchasing_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_purchasing.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qml.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qml_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qml.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qml_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmldebug_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmldevtools_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmlmodels.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmlmodels_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmlmodels.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmlmodels_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmltest.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmltest_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmltest_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmlworkerscript.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qmlworkerscript_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmlworkerscript.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3d.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3d_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick3d.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3dassetimport.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3dassetimport_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick3dassetimport.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3drender.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3drender_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick3drender.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3druntimerender.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3druntimerender_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick3druntimerender.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3dutils.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quick3dutils_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick3dutils.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quick_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickcontrols2.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickcontrols2_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickparticles_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickshapes_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quicktemplates2.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quicktemplates2_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_quickwidgets_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_remoteobjects.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_remoteobjects_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_repparser.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_repparser_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_repparser.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_repparser_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_script.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_script_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_script.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_scripttools.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_scripttools_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_scripttools.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_scxml.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_scxml_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_scxml_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_sensors.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_sensors_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_sensors_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_serialbus.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_serialbus_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_serialbus_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_serialport.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_serialport_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_sql.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_sql_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_svg.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_svg_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_svg.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_testlib_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_texttospeech.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_texttospeech_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_theme_support_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_uiplugin.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_uiplugin.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_uitools.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_uitools_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_uitools_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_virtualkeyboard.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_virtualkeyboard_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_virtualkeyboard.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_vulkan_support_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webchannel.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webchannel_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webengine.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webengine_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webengine.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webenginecore.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webenginecore_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webenginecoreheaders_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webenginecoreheaders_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webenginewidgets.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_webenginewidgets_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_websockets.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_websockets_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_websockets_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_webview.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_webview_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webview.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_windowsuiautomation_support_private.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_winextras.pri:
..\qt-everywhere-src-5.15.2\qtbase\mkspecs\modules-inst\qt_lib_winextras_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_winextras.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_xml.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_xmlpatterns.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules-inst\qt_lib_xmlpatterns_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_balsam.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_canbusutil.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_dumpcpp.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_dumpdoc.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lconvert.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lprodump.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lrelease-pro.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lrelease.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lupdate-pro.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_lupdate.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_meshdebug.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_moc.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qcollectiongenerator.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qdbuscpp2xml.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qdbusxml2cpp.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qgltf.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qhelpgenerator.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qlalr.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qml.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlcachegen.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlformat.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlimportscanner.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmllint.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlmin.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlplugindump.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlpreview.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlprofiler.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmlscene.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmltestrunner.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qmltyperegistrar.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qscxmlc.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qtattributionsscanner.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qvkgen.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_qwebengine_convert_dict.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_rcc.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_repc.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_tracegen.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_uic.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_xmlpatterns.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\modules\qt_tool_xmlpatternsvalidator.pri:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\qt_functions.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\qt_config.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\win32-msvc\qmake.conf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\qmake.conf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\spec_post.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\common\msvc-version.conf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\toolchain.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\default_pre.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\resolve_config.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\exclusive_builds_post.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\default_post.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\win32\windows.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\precompile_header.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\warn_on.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\qt.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\resources_functions.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\resources.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\moc.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\win32\opengl.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\uic.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\qmake_use.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\file_copies.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\testcase_targets.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\exceptions.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\yacc.prf:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\lex.prf:
SpotLite.pro:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebEngineWidgets.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebEngineCore.prl:
..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Positioning.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5XmlPatterns.prl:
..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Quick.prl:
..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5QmlModels.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebChannel.prl:
..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Qml.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5PrintSupport.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Widgets.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Gui.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Sql.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Network.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Core.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\qtmain.prl:
.qmake.stash:
..\..\..\..\Qt\5.15.2-msvc2019\mkspecs\features\build_pass.prf:
res\icons.qrc:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebEngineWidgetsd.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebEngineCored.prl:
..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Positioningd.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5XmlPatternsd.prl:
..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Quickd.prl:
..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5QmlModelsd.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5WebChanneld.prl:
..\qt-everywhere-src-5.15.2\qtbase\lib\Qt5Qmld.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5PrintSupportd.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Widgetsd.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Guid.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Sqld.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Networkd.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\Qt5Cored.prl:
..\..\..\..\Qt\5.15.2-msvc2019\lib\qtmaind.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SpotLite.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first  FORCE
all: debug-all release-all  FORCE
clean: debug-clean release-clean  FORCE
	-$(DEL_FILE) SpotLite.vc.pdb
	-$(DEL_FILE) SpotLite.ilk
	-$(DEL_FILE) SpotLite.idb
distclean: debug-distclean release-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\Users\William\Desktop\spotlite-webengine\uic_wrapper.bat C:\Users\William\Desktop\spotlite-webengine\uic_wrapper.bat .qmake.stash SpotLite.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
